// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: realtime/me/v1/ingest.proto

package mev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScrapeJob is the Prometheus job a scrape target belongs to.
type ScrapeJob int32

const (
	// Job is not known.
	ScrapeJob_SCRAPE_JOB_UNSPECIFIED ScrapeJob = 0
	// Linux node-exporter on a physical host.
	ScrapeJob_SCRAPE_JOB_NODE_EXPORTER ScrapeJob = 1
	// Linux node-exporter on a virtual machine.
	ScrapeJob_SCRAPE_JOB_VM_NODE_EXPORTER ScrapeJob = 2
	// Device exporter for media and accessory signals.
	ScrapeJob_SCRAPE_JOB_DEVICE_EXPORTER ScrapeJob = 3
	// Coding-agent exporter.
	ScrapeJob_SCRAPE_JOB_AGENT_EXPORTER ScrapeJob = 4
)

// Enum value maps for ScrapeJob.
var (
	ScrapeJob_name = map[int32]string{
		0: "SCRAPE_JOB_UNSPECIFIED",
		1: "SCRAPE_JOB_NODE_EXPORTER",
		2: "SCRAPE_JOB_VM_NODE_EXPORTER",
		3: "SCRAPE_JOB_DEVICE_EXPORTER",
		4: "SCRAPE_JOB_AGENT_EXPORTER",
	}
	ScrapeJob_value = map[string]int32{
		"SCRAPE_JOB_UNSPECIFIED":      0,
		"SCRAPE_JOB_NODE_EXPORTER":    1,
		"SCRAPE_JOB_VM_NODE_EXPORTER": 2,
		"SCRAPE_JOB_DEVICE_EXPORTER":  3,
		"SCRAPE_JOB_AGENT_EXPORTER":   4,
	}
)

func (x ScrapeJob) Enum() *ScrapeJob {
	p := new(ScrapeJob)
	*p = x
	return p
}

func (x ScrapeJob) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScrapeJob) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_me_v1_ingest_proto_enumTypes[0].Descriptor()
}

func (ScrapeJob) Type() protoreflect.EnumType {
	return &file_realtime_me_v1_ingest_proto_enumTypes[0]
}

func (x ScrapeJob) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScrapeJob.Descriptor instead.
func (ScrapeJob) EnumDescriptor() ([]byte, []int) {
	return file_realtime_me_v1_ingest_proto_rawDescGZIP(), []int{0}
}

// EnrollDeviceRequest describes the device seeking a gateway identity.
type EnrollDeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is the broad device category being enrolled.
	Kind DeviceKind `protobuf:"varint,1,opt,name=kind,proto3,enum=realtime.me.v1.DeviceKind" json:"kind,omitempty"`
	// role is the device's operational role.
	Role DeviceRole `protobuf:"varint,2,opt,name=role,proto3,enum=realtime.me.v1.DeviceRole" json:"role,omitempty"`
	// display_name is the human-readable device label.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// model is the hardware model reported by the operating system.
	Model         string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollDeviceRequest) Reset() {
	*x = EnrollDeviceRequest{}
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollDeviceRequest) ProtoMessage() {}

func (x *EnrollDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollDeviceRequest.ProtoReflect.Descriptor instead.
func (*EnrollDeviceRequest) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollDeviceRequest) GetKind() DeviceKind {
	if x != nil {
		return x.Kind
	}
	return DeviceKind_DEVICE_KIND_UNSPECIFIED
}

func (x *EnrollDeviceRequest) GetRole() DeviceRole {
	if x != nil {
		return x.Role
	}
	return DeviceRole_DEVICE_ROLE_UNSPECIFIED
}

func (x *EnrollDeviceRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *EnrollDeviceRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// EnrollDeviceResponse returns the gateway-owned device identity.
type EnrollDeviceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device_uid is the gateway-assigned opaque device identifier.
	DeviceUid     string `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollDeviceResponse) Reset() {
	*x = EnrollDeviceResponse{}
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollDeviceResponse) ProtoMessage() {}

func (x *EnrollDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollDeviceResponse.ProtoReflect.Descriptor instead.
func (*EnrollDeviceResponse) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollDeviceResponse) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

// ReportMobileStatusRequest carries the phone's own state and the paired watch
// snapshot, keyed by the gateway-assigned device uid.
type ReportMobileStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device_uid is the enrolled phone identity.
	DeviceUid string `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	// display_name is the human-readable phone label.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// model is the phone hardware model.
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// phone is the phone's own device state.
	Phone *PhoneState `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	// watch is the latest paired-watch snapshot, reusing the Data Layer contract.
	Watch *WatchSnapshot `protobuf:"bytes,5,opt,name=watch,proto3" json:"watch,omitempty"`
	// switch_presence is the owner's Nintendo Switch play presence, if available.
	SwitchPresence *SwitchPresence `protobuf:"bytes,6,opt,name=switch_presence,json=switchPresence,proto3" json:"switch_presence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportMobileStatusRequest) Reset() {
	*x = ReportMobileStatusRequest{}
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMobileStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMobileStatusRequest) ProtoMessage() {}

func (x *ReportMobileStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMobileStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportMobileStatusRequest) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *ReportMobileStatusRequest) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *ReportMobileStatusRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ReportMobileStatusRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ReportMobileStatusRequest) GetPhone() *PhoneState {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *ReportMobileStatusRequest) GetWatch() *WatchSnapshot {
	if x != nil {
		return x.Watch
	}
	return nil
}

func (x *ReportMobileStatusRequest) GetSwitchPresence() *SwitchPresence {
	if x != nil {
		return x.SwitchPresence
	}
	return nil
}

// ReportMobileStatusResponse is the acknowledgement of a mobile report.
type ReportMobileStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMobileStatusResponse) Reset() {
	*x = ReportMobileStatusResponse{}
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMobileStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMobileStatusResponse) ProtoMessage() {}

func (x *ReportMobileStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMobileStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportMobileStatusResponse) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_ingest_proto_rawDescGZIP(), []int{3}
}

// RegisterScrapeTargetsRequest declares the complete set of scrape targets for
// one enrolled device. Declaring an empty set removes the device from discovery,
// so a decommissioned host stops being scraped instead of failing forever.
type RegisterScrapeTargetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// targets is the complete set of endpoints Prometheus should scrape for the device.
	Targets []*ScrapeTarget `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	// device_uid is the enrolled device the targets belong to.
	DeviceUid     string `protobuf:"bytes,2,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterScrapeTargetsRequest) Reset() {
	*x = RegisterScrapeTargetsRequest{}
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterScrapeTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterScrapeTargetsRequest) ProtoMessage() {}

func (x *RegisterScrapeTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterScrapeTargetsRequest.ProtoReflect.Descriptor instead.
func (*RegisterScrapeTargetsRequest) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterScrapeTargetsRequest) GetTargets() []*ScrapeTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *RegisterScrapeTargetsRequest) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

// RegisterScrapeTargetsResponse is the acknowledgement of a registration.
type RegisterScrapeTargetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterScrapeTargetsResponse) Reset() {
	*x = RegisterScrapeTargetsResponse{}
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterScrapeTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterScrapeTargetsResponse) ProtoMessage() {}

func (x *RegisterScrapeTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterScrapeTargetsResponse.ProtoReflect.Descriptor instead.
func (*RegisterScrapeTargetsResponse) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_ingest_proto_rawDescGZIP(), []int{5}
}

// ScrapeTarget is one endpoint Prometheus scrapes. The device it belongs to, and
// every label describing that device, come from the enrollment the gateway owns;
// a caller cannot assert them here.
type ScrapeTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job is the Prometheus job the target belongs to.
	Job ScrapeJob `protobuf:"varint,1,opt,name=job,proto3,enum=realtime.me.v1.ScrapeJob" json:"job,omitempty"`
	// target is the host:port endpoint Prometheus scrapes.
	Target        string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeTarget) Reset() {
	*x = ScrapeTarget{}
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeTarget) ProtoMessage() {}

func (x *ScrapeTarget) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeTarget.ProtoReflect.Descriptor instead.
func (*ScrapeTarget) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_ingest_proto_rawDescGZIP(), []int{6}
}

func (x *ScrapeTarget) GetJob() ScrapeJob {
	if x != nil {
		return x.Job
	}
	return ScrapeJob_SCRAPE_JOB_UNSPECIFIED
}

func (x *ScrapeTarget) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_realtime_me_v1_ingest_proto protoreflect.FileDescriptor

const file_realtime_me_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x1brealtime/me/v1/ingest.proto\x12\x0erealtime.me.v1\x1a!realtime/me/v1/status_types.proto\x1a\x1arealtime/me/v1/watch.proto\"\xae\x01\n" +
	"\x13EnrollDeviceRequest\x12.\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1a.realtime.me.v1.DeviceKindR\x04kind\x12.\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1a.realtime.me.v1.DeviceRoleR\x04role\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"5\n" +
	"\x14EnrollDeviceResponse\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\"\xa3\x02\n" +
	"\x19ReportMobileStatusRequest\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x120\n" +
	"\x05phone\x18\x04 \x01(\v2\x1a.realtime.me.v1.PhoneStateR\x05phone\x123\n" +
	"\x05watch\x18\x05 \x01(\v2\x1d.realtime.me.v1.WatchSnapshotR\x05watch\x12G\n" +
	"\x0fswitch_presence\x18\x06 \x01(\v2\x1e.realtime.me.v1.SwitchPresenceR\x0eswitchPresence\"\x1c\n" +
	"\x1aReportMobileStatusResponse\"u\n" +
	"\x1cRegisterScrapeTargetsRequest\x126\n" +
	"\atargets\x18\x01 \x03(\v2\x1c.realtime.me.v1.ScrapeTargetR\atargets\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x02 \x01(\tR\tdeviceUid\"\x1f\n" +
	"\x1dRegisterScrapeTargetsResponse\"\x9e\x01\n" +
	"\fScrapeTarget\x12+\n" +
	"\x03job\x18\x01 \x01(\x0e2\x19.realtime.me.v1.ScrapeJobR\x03job\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06targetJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bR\n" +
	"device_uidR\fdisplay_nameR\x05modelR\x04kindR\x04role*\xa5\x01\n" +
	"\tScrapeJob\x12\x1a\n" +
	"\x16SCRAPE_JOB_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SCRAPE_JOB_NODE_EXPORTER\x10\x01\x12\x1f\n" +
	"\x1bSCRAPE_JOB_VM_NODE_EXPORTER\x10\x02\x12\x1e\n" +
	"\x1aSCRAPE_JOB_DEVICE_EXPORTER\x10\x03\x12\x1d\n" +
	"\x19SCRAPE_JOB_AGENT_EXPORTER\x10\x042n\n" +
	"\x11EnrollmentService\x12Y\n" +
	"\fEnrollDevice\x12#.realtime.me.v1.EnrollDeviceRequest\x1a$.realtime.me.v1.EnrollDeviceResponse2\xf2\x01\n" +
	"\rIngestService\x12k\n" +
	"\x12ReportMobileStatus\x12).realtime.me.v1.ReportMobileStatusRequest\x1a*.realtime.me.v1.ReportMobileStatusResponse\x12t\n" +
	"\x15RegisterScrapeTargets\x12,.realtime.me.v1.RegisterScrapeTargetsRequest\x1a-.realtime.me.v1.RegisterScrapeTargetsResponseB\xc2\x01\n" +
	"\x12com.realtime.me.v1B\vIngestProtoP\x01ZErealtime-me/apps/status-gateway/internal/genproto/realtime/me/v1;mev1\xa2\x02\x03RMX\xaa\x02\x0eRealtime.Me.V1\xca\x02\x0eRealtime\\Me\\V1\xe2\x02\x1aRealtime\\Me\\V1\\GPBMetadata\xea\x02\x10Realtime::Me::V1b\x06proto3"

var (
	file_realtime_me_v1_ingest_proto_rawDescOnce sync.Once
	file_realtime_me_v1_ingest_proto_rawDescData []byte
)

func file_realtime_me_v1_ingest_proto_rawDescGZIP() []byte {
	file_realtime_me_v1_ingest_proto_rawDescOnce.Do(func() {
		file_realtime_me_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtime_me_v1_ingest_proto_rawDesc), len(file_realtime_me_v1_ingest_proto_rawDesc)))
	})
	return file_realtime_me_v1_ingest_proto_rawDescData
}

var file_realtime_me_v1_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_realtime_me_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_realtime_me_v1_ingest_proto_goTypes = []any{
	(ScrapeJob)(0),                        // 0: realtime.me.v1.ScrapeJob
	(*EnrollDeviceRequest)(nil),           // 1: realtime.me.v1.EnrollDeviceRequest
	(*EnrollDeviceResponse)(nil),          // 2: realtime.me.v1.EnrollDeviceResponse
	(*ReportMobileStatusRequest)(nil),     // 3: realtime.me.v1.ReportMobileStatusRequest
	(*ReportMobileStatusResponse)(nil),    // 4: realtime.me.v1.ReportMobileStatusResponse
	(*RegisterScrapeTargetsRequest)(nil),  // 5: realtime.me.v1.RegisterScrapeTargetsRequest
	(*RegisterScrapeTargetsResponse)(nil), // 6: realtime.me.v1.RegisterScrapeTargetsResponse
	(*ScrapeTarget)(nil),                  // 7: realtime.me.v1.ScrapeTarget
	(DeviceKind)(0),                       // 8: realtime.me.v1.DeviceKind
	(DeviceRole)(0),                       // 9: realtime.me.v1.DeviceRole
	(*PhoneState)(nil),                    // 10: realtime.me.v1.PhoneState
	(*WatchSnapshot)(nil),                 // 11: realtime.me.v1.WatchSnapshot
	(*SwitchPresence)(nil),                // 12: realtime.me.v1.SwitchPresence
}
var file_realtime_me_v1_ingest_proto_depIdxs = []int32{
	8,  // 0: realtime.me.v1.EnrollDeviceRequest.kind:type_name -> realtime.me.v1.DeviceKind
	9,  // 1: realtime.me.v1.EnrollDeviceRequest.role:type_name -> realtime.me.v1.DeviceRole
	10, // 2: realtime.me.v1.ReportMobileStatusRequest.phone:type_name -> realtime.me.v1.PhoneState
	11, // 3: realtime.me.v1.ReportMobileStatusRequest.watch:type_name -> realtime.me.v1.WatchSnapshot
	12, // 4: realtime.me.v1.ReportMobileStatusRequest.switch_presence:type_name -> realtime.me.v1.SwitchPresence
	7,  // 5: realtime.me.v1.RegisterScrapeTargetsRequest.targets:type_name -> realtime.me.v1.ScrapeTarget
	0,  // 6: realtime.me.v1.ScrapeTarget.job:type_name -> realtime.me.v1.ScrapeJob
	1,  // 7: realtime.me.v1.EnrollmentService.EnrollDevice:input_type -> realtime.me.v1.EnrollDeviceRequest
	3,  // 8: realtime.me.v1.IngestService.ReportMobileStatus:input_type -> realtime.me.v1.ReportMobileStatusRequest
	5,  // 9: realtime.me.v1.IngestService.RegisterScrapeTargets:input_type -> realtime.me.v1.RegisterScrapeTargetsRequest
	2,  // 10: realtime.me.v1.EnrollmentService.EnrollDevice:output_type -> realtime.me.v1.EnrollDeviceResponse
	4,  // 11: realtime.me.v1.IngestService.ReportMobileStatus:output_type -> realtime.me.v1.ReportMobileStatusResponse
	6,  // 12: realtime.me.v1.IngestService.RegisterScrapeTargets:output_type -> realtime.me.v1.RegisterScrapeTargetsResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_realtime_me_v1_ingest_proto_init() }
func file_realtime_me_v1_ingest_proto_init() {
	if File_realtime_me_v1_ingest_proto != nil {
		return
	}
	file_realtime_me_v1_status_types_proto_init()
	file_realtime_me_v1_watch_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtime_me_v1_ingest_proto_rawDesc), len(file_realtime_me_v1_ingest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_realtime_me_v1_ingest_proto_goTypes,
		DependencyIndexes: file_realtime_me_v1_ingest_proto_depIdxs,
		EnumInfos:         file_realtime_me_v1_ingest_proto_enumTypes,
		MessageInfos:      file_realtime_me_v1_ingest_proto_msgTypes,
	}.Build()
	File_realtime_me_v1_ingest_proto = out.File
	file_realtime_me_v1_ingest_proto_goTypes = nil
	file_realtime_me_v1_ingest_proto_depIdxs = nil
}
