// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: realtime/me/v1/status.proto

package mev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GitHubSyncState is the state of GitHub status synchronization.
type GithubSyncState int32

const (
	// State is not known.
	GithubSyncState_GITHUB_SYNC_STATE_UNSPECIFIED GithubSyncState = 0
	// Synchronization is disabled because no token is configured.
	GithubSyncState_GITHUB_SYNC_STATE_DISABLED GithubSyncState = 1
	// A synchronization attempt is in progress.
	GithubSyncState_GITHUB_SYNC_STATE_PENDING GithubSyncState = 2
	// The last synchronization succeeded.
	GithubSyncState_GITHUB_SYNC_STATE_OK GithubSyncState = 3
	// The last synchronization failed.
	GithubSyncState_GITHUB_SYNC_STATE_ERROR GithubSyncState = 4
)

// Enum value maps for GithubSyncState.
var (
	GithubSyncState_name = map[int32]string{
		0: "GITHUB_SYNC_STATE_UNSPECIFIED",
		1: "GITHUB_SYNC_STATE_DISABLED",
		2: "GITHUB_SYNC_STATE_PENDING",
		3: "GITHUB_SYNC_STATE_OK",
		4: "GITHUB_SYNC_STATE_ERROR",
	}
	GithubSyncState_value = map[string]int32{
		"GITHUB_SYNC_STATE_UNSPECIFIED": 0,
		"GITHUB_SYNC_STATE_DISABLED":    1,
		"GITHUB_SYNC_STATE_PENDING":     2,
		"GITHUB_SYNC_STATE_OK":          3,
		"GITHUB_SYNC_STATE_ERROR":       4,
	}
)

func (x GithubSyncState) Enum() *GithubSyncState {
	p := new(GithubSyncState)
	*p = x
	return p
}

func (x GithubSyncState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GithubSyncState) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_me_v1_status_proto_enumTypes[0].Descriptor()
}

func (GithubSyncState) Type() protoreflect.EnumType {
	return &file_realtime_me_v1_status_proto_enumTypes[0]
}

func (x GithubSyncState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GithubSyncState.Descriptor instead.
func (GithubSyncState) EnumDescriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{0}
}

// GetPublicStatusRequest is the request for the public status document.
type GetPublicStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicStatusRequest) Reset() {
	*x = GetPublicStatusRequest{}
	mi := &file_realtime_me_v1_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicStatusRequest) ProtoMessage() {}

func (x *GetPublicStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPublicStatusRequest) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{0}
}

// GetPublicStatusResponse carries the public status document.
type GetPublicStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the public status document.
	Status        *PublicStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicStatusResponse) Reset() {
	*x = GetPublicStatusResponse{}
	mi := &file_realtime_me_v1_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicStatusResponse) ProtoMessage() {}

func (x *GetPublicStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPublicStatusResponse) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublicStatusResponse) GetStatus() *PublicStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// GetInternalStatusRequest is the request for the internal status document.
type GetInternalStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInternalStatusRequest) Reset() {
	*x = GetInternalStatusRequest{}
	mi := &file_realtime_me_v1_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInternalStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInternalStatusRequest) ProtoMessage() {}

func (x *GetInternalStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInternalStatusRequest.ProtoReflect.Descriptor instead.
func (*GetInternalStatusRequest) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{2}
}

// GetInternalStatusResponse carries the internal status document.
type GetInternalStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the internal status document.
	Status        *InternalStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInternalStatusResponse) Reset() {
	*x = GetInternalStatusResponse{}
	mi := &file_realtime_me_v1_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInternalStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInternalStatusResponse) ProtoMessage() {}

func (x *GetInternalStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInternalStatusResponse.ProtoReflect.Descriptor instead.
func (*GetInternalStatusResponse) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{3}
}

func (x *GetInternalStatusResponse) GetStatus() *InternalStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// DeviceState is a device's current status on a read surface.
type DeviceState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device_uid is the gateway-assigned device identity.
	DeviceUid string `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	// display_name is the human-readable device label.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// model is the device hardware model.
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// kind is the device category.
	Kind DeviceKind `protobuf:"varint,4,opt,name=kind,proto3,enum=realtime.me.v1.DeviceKind" json:"kind,omitempty"`
	// role is the device's operational role.
	Role DeviceRole `protobuf:"varint,5,opt,name=role,proto3,enum=realtime.me.v1.DeviceRole" json:"role,omitempty"`
	// state is the device's reachability.
	State OnlineState `protobuf:"varint,6,opt,name=state,proto3,enum=realtime.me.v1.OnlineState" json:"state,omitempty"`
	// metrics are the device's latest OpenTelemetry-named metrics.
	Metrics []*MetricSample `protobuf:"bytes,7,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// media is the currently playing media, if any.
	Media *MediaStatus `protobuf:"bytes,8,opt,name=media,proto3" json:"media,omitempty"`
	// accessories are connected peripherals.
	Accessories []*Accessory `protobuf:"bytes,9,rep,name=accessories,proto3" json:"accessories,omitempty"`
	// update_time is when this device's status was last refreshed.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceState) Reset() {
	*x = DeviceState{}
	mi := &file_realtime_me_v1_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceState) ProtoMessage() {}

func (x *DeviceState) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceState.ProtoReflect.Descriptor instead.
func (*DeviceState) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceState) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *DeviceState) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DeviceState) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceState) GetKind() DeviceKind {
	if x != nil {
		return x.Kind
	}
	return DeviceKind_DEVICE_KIND_UNSPECIFIED
}

func (x *DeviceState) GetRole() DeviceRole {
	if x != nil {
		return x.Role
	}
	return DeviceRole_DEVICE_ROLE_UNSPECIFIED
}

func (x *DeviceState) GetState() OnlineState {
	if x != nil {
		return x.State
	}
	return OnlineState_ONLINE_STATE_UNSPECIFIED
}

func (x *DeviceState) GetMetrics() []*MetricSample {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *DeviceState) GetMedia() *MediaStatus {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *DeviceState) GetAccessories() []*Accessory {
	if x != nil {
		return x.Accessories
	}
	return nil
}

func (x *DeviceState) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// MobileState is the phone-and-watch pair's current status.
type MobileState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device_uid is the gateway-assigned phone identity.
	DeviceUid string `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	// display_name is the human-readable phone label.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// model is the phone hardware model.
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// phone is the phone's own device state.
	Phone *PhoneState `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	// watch is the latest paired-watch snapshot.
	Watch *WatchSnapshot `protobuf:"bytes,5,opt,name=watch,proto3" json:"watch,omitempty"`
	// update_time is when this status was last refreshed.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MobileState) Reset() {
	*x = MobileState{}
	mi := &file_realtime_me_v1_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MobileState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileState) ProtoMessage() {}

func (x *MobileState) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileState.ProtoReflect.Descriptor instead.
func (*MobileState) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{5}
}

func (x *MobileState) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *MobileState) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MobileState) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *MobileState) GetPhone() *PhoneState {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *MobileState) GetWatch() *WatchSnapshot {
	if x != nil {
		return x.Watch
	}
	return nil
}

func (x *MobileState) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// Agent is a coding agent's current status on a read surface. It never exposes
// the underlying task text or any internal session identifier.
type Agent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uid is the gateway-assigned opaque agent identity.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// kind is the agent kind, such as "codex" or "claude".
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// device_uid is the host the agent runs on.
	DeviceUid string `protobuf:"bytes,3,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	// display_name is the human-readable host label.
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// state is the agent's run state.
	State AgentState `protobuf:"varint,5,opt,name=state,proto3,enum=realtime.me.v1.AgentState" json:"state,omitempty"`
	// budget_remaining_percent is the remaining budget from 0 to 100, if known.
	BudgetRemainingPercent *int32 `protobuf:"varint,6,opt,name=budget_remaining_percent,json=budgetRemainingPercent,proto3,oneof" json:"budget_remaining_percent,omitempty"`
	// update_time is when this agent's status was last refreshed.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// model is the model the agent is currently running, such as "claude-opus-4-8".
	Model string `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	// subagent_count is how many sub-agents the agent has working right now.
	SubagentCount int32 `protobuf:"varint,9,opt,name=subagent_count,json=subagentCount,proto3" json:"subagent_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_realtime_me_v1_status_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{6}
}

func (x *Agent) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Agent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Agent) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *Agent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Agent) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_AGENT_STATE_UNSPECIFIED
}

func (x *Agent) GetBudgetRemainingPercent() int32 {
	if x != nil && x.BudgetRemainingPercent != nil {
		return *x.BudgetRemainingPercent
	}
	return 0
}

func (x *Agent) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Agent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Agent) GetSubagentCount() int32 {
	if x != nil {
		return x.SubagentCount
	}
	return 0
}

// GithubStatus is the public view of GitHub status synchronization.
type GithubStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enabled is whether GitHub synchronization is configured.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// state is the current synchronization state.
	State GithubSyncState `protobuf:"varint,2,opt,name=state,proto3,enum=realtime.me.v1.GithubSyncState" json:"state,omitempty"`
	// emoji is the emoji shown on the current GitHub status.
	Emoji string `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`
	// message is the message shown on the current GitHub status.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// update_time is when the GitHub status last synchronized successfully.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubStatus) Reset() {
	*x = GithubStatus{}
	mi := &file_realtime_me_v1_status_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubStatus) ProtoMessage() {}

func (x *GithubStatus) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubStatus.ProtoReflect.Descriptor instead.
func (*GithubStatus) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{7}
}

func (x *GithubStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GithubStatus) GetState() GithubSyncState {
	if x != nil {
		return x.State
	}
	return GithubSyncState_GITHUB_SYNC_STATE_UNSPECIFIED
}

func (x *GithubStatus) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *GithubStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GithubStatus) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// GithubSyncDetail is the authenticated view including error diagnostics.
type GithubSyncDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// configured is whether a GitHub token is present.
	Configured bool `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	// state is the current synchronization state.
	State GithubSyncState `protobuf:"varint,2,opt,name=state,proto3,enum=realtime.me.v1.GithubSyncState" json:"state,omitempty"`
	// emoji is the emoji on the current GitHub status.
	Emoji string `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`
	// message is the message on the current GitHub status.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// last_success_time is when synchronization last succeeded.
	LastSuccessTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_success_time,json=lastSuccessTime,proto3" json:"last_success_time,omitempty"`
	// last_error_time is when synchronization last failed.
	LastErrorTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_error_time,json=lastErrorTime,proto3" json:"last_error_time,omitempty"`
	// last_error is the most recent synchronization error.
	LastError string `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// last_attempt_time is when synchronization was last attempted; it drives the
	// minimum-interval rate limit.
	LastAttemptTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_attempt_time,json=lastAttemptTime,proto3" json:"last_attempt_time,omitempty"`
	// last_signature is a fingerprint of the last published status used to skip
	// redundant updates.
	LastSignature string `protobuf:"bytes,9,opt,name=last_signature,json=lastSignature,proto3" json:"last_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubSyncDetail) Reset() {
	*x = GithubSyncDetail{}
	mi := &file_realtime_me_v1_status_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubSyncDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubSyncDetail) ProtoMessage() {}

func (x *GithubSyncDetail) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubSyncDetail.ProtoReflect.Descriptor instead.
func (*GithubSyncDetail) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{8}
}

func (x *GithubSyncDetail) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *GithubSyncDetail) GetState() GithubSyncState {
	if x != nil {
		return x.State
	}
	return GithubSyncState_GITHUB_SYNC_STATE_UNSPECIFIED
}

func (x *GithubSyncDetail) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *GithubSyncDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GithubSyncDetail) GetLastSuccessTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccessTime
	}
	return nil
}

func (x *GithubSyncDetail) GetLastErrorTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastErrorTime
	}
	return nil
}

func (x *GithubSyncDetail) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *GithubSyncDetail) GetLastAttemptTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAttemptTime
	}
	return nil
}

func (x *GithubSyncDetail) GetLastSignature() string {
	if x != nil {
		return x.LastSignature
	}
	return ""
}

// PublicStatus is the unauthenticated status document.
type PublicStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server is the always-on server's status.
	Server *DeviceState `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// mobile is the phone-and-watch pair's status.
	Mobile *MobileState `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// devices are the non-server devices' statuses.
	Devices []*DeviceState `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	// agents are the currently visible coding agents.
	Agents []*Agent `protobuf:"bytes,4,rep,name=agents,proto3" json:"agents,omitempty"`
	// github is the public GitHub synchronization status.
	Github *GithubStatus `protobuf:"bytes,5,opt,name=github,proto3" json:"github,omitempty"`
	// update_time is when this document was assembled.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicStatus) Reset() {
	*x = PublicStatus{}
	mi := &file_realtime_me_v1_status_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicStatus) ProtoMessage() {}

func (x *PublicStatus) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicStatus.ProtoReflect.Descriptor instead.
func (*PublicStatus) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{9}
}

func (x *PublicStatus) GetServer() *DeviceState {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *PublicStatus) GetMobile() *MobileState {
	if x != nil {
		return x.Mobile
	}
	return nil
}

func (x *PublicStatus) GetDevices() []*DeviceState {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *PublicStatus) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *PublicStatus) GetGithub() *GithubStatus {
	if x != nil {
		return x.Github
	}
	return nil
}

func (x *PublicStatus) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// InternalStatus is the authenticated status document with sync diagnostics.
type InternalStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server is the always-on server's status.
	Server *DeviceState `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// mobile is the phone-and-watch pair's status.
	Mobile *MobileState `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// devices are the non-server devices' statuses.
	Devices []*DeviceState `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	// agents are the currently visible coding agents.
	Agents []*Agent `protobuf:"bytes,4,rep,name=agents,proto3" json:"agents,omitempty"`
	// github is the detailed GitHub synchronization status.
	Github *GithubSyncDetail `protobuf:"bytes,5,opt,name=github,proto3" json:"github,omitempty"`
	// update_time is when this document was assembled.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalStatus) Reset() {
	*x = InternalStatus{}
	mi := &file_realtime_me_v1_status_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalStatus) ProtoMessage() {}

func (x *InternalStatus) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalStatus.ProtoReflect.Descriptor instead.
func (*InternalStatus) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_proto_rawDescGZIP(), []int{10}
}

func (x *InternalStatus) GetServer() *DeviceState {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *InternalStatus) GetMobile() *MobileState {
	if x != nil {
		return x.Mobile
	}
	return nil
}

func (x *InternalStatus) GetDevices() []*DeviceState {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *InternalStatus) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *InternalStatus) GetGithub() *GithubSyncDetail {
	if x != nil {
		return x.Github
	}
	return nil
}

func (x *InternalStatus) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

var File_realtime_me_v1_status_proto protoreflect.FileDescriptor

const file_realtime_me_v1_status_proto_rawDesc = "" +
	"\n" +
	"\x1brealtime/me/v1/status.proto\x12\x0erealtime.me.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!realtime/me/v1/status_types.proto\x1a\x1arealtime/me/v1/watch.proto\"\x18\n" +
	"\x16GetPublicStatusRequest\"O\n" +
	"\x17GetPublicStatusResponse\x124\n" +
	"\x06status\x18\x01 \x01(\v2\x1c.realtime.me.v1.PublicStatusR\x06status\"\x1a\n" +
	"\x18GetInternalStatusRequest\"S\n" +
	"\x19GetInternalStatusResponse\x126\n" +
	"\x06status\x18\x01 \x01(\v2\x1e.realtime.me.v1.InternalStatusR\x06status\"\xed\x03\n" +
	"\vDeviceState\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12.\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1a.realtime.me.v1.DeviceKindR\x04kind\x12.\n" +
	"\x04role\x18\x05 \x01(\x0e2\x1a.realtime.me.v1.DeviceRoleR\x04role\x121\n" +
	"\x05state\x18\x06 \x01(\x0e2\x1b.realtime.me.v1.OnlineStateR\x05state\x126\n" +
	"\ametrics\x18\a \x03(\v2\x1c.realtime.me.v1.MetricSampleR\ametrics\x121\n" +
	"\x05media\x18\b \x01(\v2\x1b.realtime.me.v1.MediaStatusR\x05media\x12;\n" +
	"\vaccessories\x18\t \x03(\v2\x19.realtime.me.v1.AccessoryR\vaccessories\x12;\n" +
	"\vupdate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTimeJ\x04\b\n" +
	"\x10\vR\bchildren\"\x89\x02\n" +
	"\vMobileState\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x120\n" +
	"\x05phone\x18\x04 \x01(\v2\x1a.realtime.me.v1.PhoneStateR\x05phone\x123\n" +
	"\x05watch\x18\x05 \x01(\v2\x1d.realtime.me.v1.WatchSnapshotR\x05watch\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xf7\x02\n" +
	"\x05Agent\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x03 \x01(\tR\tdeviceUid\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x120\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1a.realtime.me.v1.AgentStateR\x05state\x12=\n" +
	"\x18budget_remaining_percent\x18\x06 \x01(\x05H\x00R\x16budgetRemainingPercent\x88\x01\x01\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12%\n" +
	"\x0esubagent_count\x18\t \x01(\x05R\rsubagentCountB\x1b\n" +
	"\x19_budget_remaining_percent\"\xcc\x01\n" +
	"\fGithubStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.realtime.me.v1.GithubSyncStateR\x05state\x12\x14\n" +
	"\x05emoji\x18\x03 \x01(\tR\x05emoji\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12;\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xb3\x03\n" +
	"\x10GithubSyncDetail\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.realtime.me.v1.GithubSyncStateR\x05state\x12\x14\n" +
	"\x05emoji\x18\x03 \x01(\tR\x05emoji\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12F\n" +
	"\x11last_success_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastSuccessTime\x12B\n" +
	"\x0flast_error_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastErrorTime\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\x12F\n" +
	"\x11last_attempt_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0flastAttemptTime\x12%\n" +
	"\x0elast_signature\x18\t \x01(\tR\rlastSignature\"\xd1\x02\n" +
	"\fPublicStatus\x123\n" +
	"\x06server\x18\x01 \x01(\v2\x1b.realtime.me.v1.DeviceStateR\x06server\x123\n" +
	"\x06mobile\x18\x02 \x01(\v2\x1b.realtime.me.v1.MobileStateR\x06mobile\x125\n" +
	"\adevices\x18\x03 \x03(\v2\x1b.realtime.me.v1.DeviceStateR\adevices\x12-\n" +
	"\x06agents\x18\x04 \x03(\v2\x15.realtime.me.v1.AgentR\x06agents\x124\n" +
	"\x06github\x18\x05 \x01(\v2\x1c.realtime.me.v1.GithubStatusR\x06github\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xd7\x02\n" +
	"\x0eInternalStatus\x123\n" +
	"\x06server\x18\x01 \x01(\v2\x1b.realtime.me.v1.DeviceStateR\x06server\x123\n" +
	"\x06mobile\x18\x02 \x01(\v2\x1b.realtime.me.v1.MobileStateR\x06mobile\x125\n" +
	"\adevices\x18\x03 \x03(\v2\x1b.realtime.me.v1.DeviceStateR\adevices\x12-\n" +
	"\x06agents\x18\x04 \x03(\v2\x15.realtime.me.v1.AgentR\x06agents\x128\n" +
	"\x06github\x18\x05 \x01(\v2 .realtime.me.v1.GithubSyncDetailR\x06github\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime*\xaa\x01\n" +
	"\x0fGithubSyncState\x12!\n" +
	"\x1dGITHUB_SYNC_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aGITHUB_SYNC_STATE_DISABLED\x10\x01\x12\x1d\n" +
	"\x19GITHUB_SYNC_STATE_PENDING\x10\x02\x12\x18\n" +
	"\x14GITHUB_SYNC_STATE_OK\x10\x03\x12\x1b\n" +
	"\x17GITHUB_SYNC_STATE_ERROR\x10\x042\xdd\x01\n" +
	"\rStatusService\x12b\n" +
	"\x0fGetPublicStatus\x12&.realtime.me.v1.GetPublicStatusRequest\x1a'.realtime.me.v1.GetPublicStatusResponse\x12h\n" +
	"\x11GetInternalStatus\x12(.realtime.me.v1.GetInternalStatusRequest\x1a).realtime.me.v1.GetInternalStatusResponseB\xc2\x01\n" +
	"\x12com.realtime.me.v1B\vStatusProtoP\x01ZErealtime-me/apps/status-gateway/internal/genproto/realtime/me/v1;mev1\xa2\x02\x03RMX\xaa\x02\x0eRealtime.Me.V1\xca\x02\x0eRealtime\\Me\\V1\xe2\x02\x1aRealtime\\Me\\V1\\GPBMetadata\xea\x02\x10Realtime::Me::V1b\x06proto3"

var (
	file_realtime_me_v1_status_proto_rawDescOnce sync.Once
	file_realtime_me_v1_status_proto_rawDescData []byte
)

func file_realtime_me_v1_status_proto_rawDescGZIP() []byte {
	file_realtime_me_v1_status_proto_rawDescOnce.Do(func() {
		file_realtime_me_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtime_me_v1_status_proto_rawDesc), len(file_realtime_me_v1_status_proto_rawDesc)))
	})
	return file_realtime_me_v1_status_proto_rawDescData
}

var file_realtime_me_v1_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_realtime_me_v1_status_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_realtime_me_v1_status_proto_goTypes = []any{
	(GithubSyncState)(0),              // 0: realtime.me.v1.GithubSyncState
	(*GetPublicStatusRequest)(nil),    // 1: realtime.me.v1.GetPublicStatusRequest
	(*GetPublicStatusResponse)(nil),   // 2: realtime.me.v1.GetPublicStatusResponse
	(*GetInternalStatusRequest)(nil),  // 3: realtime.me.v1.GetInternalStatusRequest
	(*GetInternalStatusResponse)(nil), // 4: realtime.me.v1.GetInternalStatusResponse
	(*DeviceState)(nil),               // 5: realtime.me.v1.DeviceState
	(*MobileState)(nil),               // 6: realtime.me.v1.MobileState
	(*Agent)(nil),                     // 7: realtime.me.v1.Agent
	(*GithubStatus)(nil),              // 8: realtime.me.v1.GithubStatus
	(*GithubSyncDetail)(nil),          // 9: realtime.me.v1.GithubSyncDetail
	(*PublicStatus)(nil),              // 10: realtime.me.v1.PublicStatus
	(*InternalStatus)(nil),            // 11: realtime.me.v1.InternalStatus
	(DeviceKind)(0),                   // 12: realtime.me.v1.DeviceKind
	(DeviceRole)(0),                   // 13: realtime.me.v1.DeviceRole
	(OnlineState)(0),                  // 14: realtime.me.v1.OnlineState
	(*MetricSample)(nil),              // 15: realtime.me.v1.MetricSample
	(*MediaStatus)(nil),               // 16: realtime.me.v1.MediaStatus
	(*Accessory)(nil),                 // 17: realtime.me.v1.Accessory
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
	(*PhoneState)(nil),                // 19: realtime.me.v1.PhoneState
	(*WatchSnapshot)(nil),             // 20: realtime.me.v1.WatchSnapshot
	(AgentState)(0),                   // 21: realtime.me.v1.AgentState
}
var file_realtime_me_v1_status_proto_depIdxs = []int32{
	10, // 0: realtime.me.v1.GetPublicStatusResponse.status:type_name -> realtime.me.v1.PublicStatus
	11, // 1: realtime.me.v1.GetInternalStatusResponse.status:type_name -> realtime.me.v1.InternalStatus
	12, // 2: realtime.me.v1.DeviceState.kind:type_name -> realtime.me.v1.DeviceKind
	13, // 3: realtime.me.v1.DeviceState.role:type_name -> realtime.me.v1.DeviceRole
	14, // 4: realtime.me.v1.DeviceState.state:type_name -> realtime.me.v1.OnlineState
	15, // 5: realtime.me.v1.DeviceState.metrics:type_name -> realtime.me.v1.MetricSample
	16, // 6: realtime.me.v1.DeviceState.media:type_name -> realtime.me.v1.MediaStatus
	17, // 7: realtime.me.v1.DeviceState.accessories:type_name -> realtime.me.v1.Accessory
	18, // 8: realtime.me.v1.DeviceState.update_time:type_name -> google.protobuf.Timestamp
	19, // 9: realtime.me.v1.MobileState.phone:type_name -> realtime.me.v1.PhoneState
	20, // 10: realtime.me.v1.MobileState.watch:type_name -> realtime.me.v1.WatchSnapshot
	18, // 11: realtime.me.v1.MobileState.update_time:type_name -> google.protobuf.Timestamp
	21, // 12: realtime.me.v1.Agent.state:type_name -> realtime.me.v1.AgentState
	18, // 13: realtime.me.v1.Agent.update_time:type_name -> google.protobuf.Timestamp
	0,  // 14: realtime.me.v1.GithubStatus.state:type_name -> realtime.me.v1.GithubSyncState
	18, // 15: realtime.me.v1.GithubStatus.update_time:type_name -> google.protobuf.Timestamp
	0,  // 16: realtime.me.v1.GithubSyncDetail.state:type_name -> realtime.me.v1.GithubSyncState
	18, // 17: realtime.me.v1.GithubSyncDetail.last_success_time:type_name -> google.protobuf.Timestamp
	18, // 18: realtime.me.v1.GithubSyncDetail.last_error_time:type_name -> google.protobuf.Timestamp
	18, // 19: realtime.me.v1.GithubSyncDetail.last_attempt_time:type_name -> google.protobuf.Timestamp
	5,  // 20: realtime.me.v1.PublicStatus.server:type_name -> realtime.me.v1.DeviceState
	6,  // 21: realtime.me.v1.PublicStatus.mobile:type_name -> realtime.me.v1.MobileState
	5,  // 22: realtime.me.v1.PublicStatus.devices:type_name -> realtime.me.v1.DeviceState
	7,  // 23: realtime.me.v1.PublicStatus.agents:type_name -> realtime.me.v1.Agent
	8,  // 24: realtime.me.v1.PublicStatus.github:type_name -> realtime.me.v1.GithubStatus
	18, // 25: realtime.me.v1.PublicStatus.update_time:type_name -> google.protobuf.Timestamp
	5,  // 26: realtime.me.v1.InternalStatus.server:type_name -> realtime.me.v1.DeviceState
	6,  // 27: realtime.me.v1.InternalStatus.mobile:type_name -> realtime.me.v1.MobileState
	5,  // 28: realtime.me.v1.InternalStatus.devices:type_name -> realtime.me.v1.DeviceState
	7,  // 29: realtime.me.v1.InternalStatus.agents:type_name -> realtime.me.v1.Agent
	9,  // 30: realtime.me.v1.InternalStatus.github:type_name -> realtime.me.v1.GithubSyncDetail
	18, // 31: realtime.me.v1.InternalStatus.update_time:type_name -> google.protobuf.Timestamp
	1,  // 32: realtime.me.v1.StatusService.GetPublicStatus:input_type -> realtime.me.v1.GetPublicStatusRequest
	3,  // 33: realtime.me.v1.StatusService.GetInternalStatus:input_type -> realtime.me.v1.GetInternalStatusRequest
	2,  // 34: realtime.me.v1.StatusService.GetPublicStatus:output_type -> realtime.me.v1.GetPublicStatusResponse
	4,  // 35: realtime.me.v1.StatusService.GetInternalStatus:output_type -> realtime.me.v1.GetInternalStatusResponse
	34, // [34:36] is the sub-list for method output_type
	32, // [32:34] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_realtime_me_v1_status_proto_init() }
func file_realtime_me_v1_status_proto_init() {
	if File_realtime_me_v1_status_proto != nil {
		return
	}
	file_realtime_me_v1_status_types_proto_init()
	file_realtime_me_v1_watch_proto_init()
	file_realtime_me_v1_status_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtime_me_v1_status_proto_rawDesc), len(file_realtime_me_v1_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realtime_me_v1_status_proto_goTypes,
		DependencyIndexes: file_realtime_me_v1_status_proto_depIdxs,
		EnumInfos:         file_realtime_me_v1_status_proto_enumTypes,
		MessageInfos:      file_realtime_me_v1_status_proto_msgTypes,
	}.Build()
	File_realtime_me_v1_status_proto = out.File
	file_realtime_me_v1_status_proto_goTypes = nil
	file_realtime_me_v1_status_proto_depIdxs = nil
}
