// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: realtime/me/v1/profile.proto

package mev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetProfileRequest is the request for the owner's identity.
type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_realtime_me_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_profile_proto_rawDescGZIP(), []int{0}
}

// GetProfileResponse carries the owner's identity.
type GetProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// profile is the site owner's public identity.
	Profile       *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_realtime_me_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// Profile is the site owner's public identity: who the page belongs to, and how
// to reach them. It says nothing about what the owner has built — that is a
// project, and ProjectsService serves those.
type Profile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// display_name is the human-readable name shown in the topbar.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// avatar_url is the URL of the profile picture.
	AvatarUrl string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// github_login is the owner's GitHub username.
	GithubLogin string `protobuf:"bytes,6,opt,name=github_login,json=githubLogin,proto3" json:"github_login,omitempty"`
	// links are the owner's public contact links.
	Links         []*ProfileLink `protobuf:"bytes,7,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_realtime_me_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *Profile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Profile) GetGithubLogin() string {
	if x != nil {
		return x.GithubLogin
	}
	return ""
}

func (x *Profile) GetLinks() []*ProfileLink {
	if x != nil {
		return x.Links
	}
	return nil
}

// ProfileLink is one public contact link, such as an email address or a social
// handle.
type ProfileLink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// label is the human-readable link text, used as the icon's accessible name.
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// uri is the link target.
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// platform is a lowercase platform key used to pick an icon, such as
	// "github", "email", or "website". Unknown values fall back to a generic icon.
	Platform      string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileLink) Reset() {
	*x = ProfileLink{}
	mi := &file_realtime_me_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileLink) ProtoMessage() {}

func (x *ProfileLink) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileLink.ProtoReflect.Descriptor instead.
func (*ProfileLink) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileLink) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ProfileLink) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ProfileLink) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_realtime_me_v1_profile_proto protoreflect.FileDescriptor

const file_realtime_me_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x1crealtime/me/v1/profile.proto\x12\x0erealtime.me.v1\"\x13\n" +
	"\x11GetProfileRequest\"G\n" +
	"\x12GetProfileResponse\x121\n" +
	"\aprofile\x18\x01 \x01(\v2\x17.realtime.me.v1.ProfileR\aprofile\"\xcc\x01\n" +
	"\aProfile\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12!\n" +
	"\fgithub_login\x18\x06 \x01(\tR\vgithubLogin\x121\n" +
	"\x05links\x18\a \x03(\v2\x1b.realtime.me.v1.ProfileLinkR\x05linksJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x05\x10\x06R\bheadlineR\x03bioR\blocation\"Q\n" +
	"\vProfileLink\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform2e\n" +
	"\x0eProfileService\x12S\n" +
	"\n" +
	"GetProfile\x12!.realtime.me.v1.GetProfileRequest\x1a\".realtime.me.v1.GetProfileResponseB\xc3\x01\n" +
	"\x12com.realtime.me.v1B\fProfileProtoP\x01ZEgithub.com/pood1e/realtime-me/services/status/internal/genproto/realtime/me/v1;mev1\xa2\x02\x03RMX\xaa\x02\x0eRealtime.Me.V1\xca\x02\x0eRealtime\\Me\\V1\xe2\x02\x1aRealtime\\Me\\V1\\GPBMetadata\xea\x02\x10Realtime::Me::V1b\x06proto3"

var (
	file_realtime_me_v1_profile_proto_rawDescOnce sync.Once
	file_realtime_me_v1_profile_proto_rawDescData []byte
)

func file_realtime_me_v1_profile_proto_rawDescGZIP() []byte {
	file_realtime_me_v1_profile_proto_rawDescOnce.Do(func() {
		file_realtime_me_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtime_me_v1_profile_proto_rawDesc), len(file_realtime_me_v1_profile_proto_rawDesc)))
	})
	return file_realtime_me_v1_profile_proto_rawDescData
}

var file_realtime_me_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_realtime_me_v1_profile_proto_goTypes = []any{
	(*GetProfileRequest)(nil),  // 0: realtime.me.v1.GetProfileRequest
	(*GetProfileResponse)(nil), // 1: realtime.me.v1.GetProfileResponse
	(*Profile)(nil),            // 2: realtime.me.v1.Profile
	(*ProfileLink)(nil),        // 3: realtime.me.v1.ProfileLink
}
var file_realtime_me_v1_profile_proto_depIdxs = []int32{
	2, // 0: realtime.me.v1.GetProfileResponse.profile:type_name -> realtime.me.v1.Profile
	3, // 1: realtime.me.v1.Profile.links:type_name -> realtime.me.v1.ProfileLink
	0, // 2: realtime.me.v1.ProfileService.GetProfile:input_type -> realtime.me.v1.GetProfileRequest
	1, // 3: realtime.me.v1.ProfileService.GetProfile:output_type -> realtime.me.v1.GetProfileResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_realtime_me_v1_profile_proto_init() }
func file_realtime_me_v1_profile_proto_init() {
	if File_realtime_me_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtime_me_v1_profile_proto_rawDesc), len(file_realtime_me_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realtime_me_v1_profile_proto_goTypes,
		DependencyIndexes: file_realtime_me_v1_profile_proto_depIdxs,
		MessageInfos:      file_realtime_me_v1_profile_proto_msgTypes,
	}.Build()
	File_realtime_me_v1_profile_proto = out.File
	file_realtime_me_v1_profile_proto_goTypes = nil
	file_realtime_me_v1_profile_proto_depIdxs = nil
}
