// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: realtime/me/v1/projects.proto

package mev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProjectVisibility describes the source repository's visibility on GitHub.
type ProjectVisibility int32

const (
	// Visibility is not known.
	ProjectVisibility_PROJECT_VISIBILITY_UNSPECIFIED ProjectVisibility = 0
	// The repository is publicly visible on GitHub.
	ProjectVisibility_PROJECT_VISIBILITY_PUBLIC ProjectVisibility = 1
	// The repository is private on GitHub.
	ProjectVisibility_PROJECT_VISIBILITY_PRIVATE ProjectVisibility = 2
)

// Enum value maps for ProjectVisibility.
var (
	ProjectVisibility_name = map[int32]string{
		0: "PROJECT_VISIBILITY_UNSPECIFIED",
		1: "PROJECT_VISIBILITY_PUBLIC",
		2: "PROJECT_VISIBILITY_PRIVATE",
	}
	ProjectVisibility_value = map[string]int32{
		"PROJECT_VISIBILITY_UNSPECIFIED": 0,
		"PROJECT_VISIBILITY_PUBLIC":      1,
		"PROJECT_VISIBILITY_PRIVATE":     2,
	}
)

func (x ProjectVisibility) Enum() *ProjectVisibility {
	p := new(ProjectVisibility)
	*p = x
	return p
}

func (x ProjectVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_me_v1_projects_proto_enumTypes[0].Descriptor()
}

func (ProjectVisibility) Type() protoreflect.EnumType {
	return &file_realtime_me_v1_projects_proto_enumTypes[0]
}

func (x ProjectVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectVisibility.Descriptor instead.
func (ProjectVisibility) EnumDescriptor() ([]byte, []int) {
	return file_realtime_me_v1_projects_proto_rawDescGZIP(), []int{0}
}

// ListProjectsRequest is the request for the curated projects.
type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_realtime_me_v1_projects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_projects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_projects_proto_rawDescGZIP(), []int{0}
}

// ListProjectsResponse carries the curated projects in display order.
type ListProjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// projects are the curated GitHub projects in display order.
	Projects      []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_realtime_me_v1_projects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_projects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_projects_proto_rawDescGZIP(), []int{1}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

// Project is one curated GitHub repository presented as a personal project.
type Project struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uid is the system-assigned opaque identifier for this project.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// display_name is the shown project title; it defaults to the repository name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// description is the repository's own short description from GitHub.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// summary is the owner's own blurb for this project, shown on the card in place
	// of the repository's GitHub description. It is written by hand and is empty
	// when none has been written.
	Summary string `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	// visibility indicates whether the source repository is public or private.
	Visibility ProjectVisibility `protobuf:"varint,5,opt,name=visibility,proto3,enum=realtime.me.v1.ProjectVisibility" json:"visibility,omitempty"`
	// primary_language is the repository's main programming language.
	PrimaryLanguage string `protobuf:"bytes,6,opt,name=primary_language,json=primaryLanguage,proto3" json:"primary_language,omitempty"`
	// topics are the repository topics used as tags.
	Topics []string `protobuf:"bytes,7,rep,name=topics,proto3" json:"topics,omitempty"`
	// star_count is the repository's stargazer count.
	StarCount int32 `protobuf:"varint,8,opt,name=star_count,json=starCount,proto3" json:"star_count,omitempty"`
	// repository_url is the GitHub page for the repository. It is omitted for
	// private projects on the public surface.
	RepositoryUrl string `protobuf:"bytes,9,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	// homepage_url is the project's homepage or live demo, if any.
	HomepageUrl string `protobuf:"bytes,10,opt,name=homepage_url,json=homepageUrl,proto3" json:"homepage_url,omitempty"`
	// last_push_time is the most recent push to the repository.
	LastPushTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_push_time,json=lastPushTime,proto3" json:"last_push_time,omitempty"`
	// create_time is when the repository was created on GitHub.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// archived is true when the source repository is archived (read-only) on GitHub.
	Archived bool `protobuf:"varint,13,opt,name=archived,proto3" json:"archived,omitempty"`
	// languages is the repository's language breakdown by source bytes, ordered
	// from the largest share to the smallest.
	Languages []*LanguageShare `protobuf:"bytes,14,rep,name=languages,proto3" json:"languages,omitempty"`
	// commit_activity is the weekly commit counts for roughly the last year,
	// oldest week first, used to draw a contribution sparkline.
	CommitActivity []int32 `protobuf:"varint,15,rep,packed,name=commit_activity,json=commitActivity,proto3" json:"commit_activity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_realtime_me_v1_projects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_projects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_projects_proto_rawDescGZIP(), []int{2}
}

func (x *Project) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Project) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Project) GetVisibility() ProjectVisibility {
	if x != nil {
		return x.Visibility
	}
	return ProjectVisibility_PROJECT_VISIBILITY_UNSPECIFIED
}

func (x *Project) GetPrimaryLanguage() string {
	if x != nil {
		return x.PrimaryLanguage
	}
	return ""
}

func (x *Project) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Project) GetStarCount() int32 {
	if x != nil {
		return x.StarCount
	}
	return 0
}

func (x *Project) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *Project) GetHomepageUrl() string {
	if x != nil {
		return x.HomepageUrl
	}
	return ""
}

func (x *Project) GetLastPushTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPushTime
	}
	return nil
}

func (x *Project) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Project) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Project) GetLanguages() []*LanguageShare {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *Project) GetCommitActivity() []int32 {
	if x != nil {
		return x.CommitActivity
	}
	return nil
}

// LanguageShare is one programming language's share of a repository, measured
// in source bytes.
type LanguageShare struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the language name, for example "TypeScript".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// bytes is the amount of source attributed to this language, in bytes.
	Bytes         int64 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageShare) Reset() {
	*x = LanguageShare{}
	mi := &file_realtime_me_v1_projects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageShare) ProtoMessage() {}

func (x *LanguageShare) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_projects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageShare.ProtoReflect.Descriptor instead.
func (*LanguageShare) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_projects_proto_rawDescGZIP(), []int{3}
}

func (x *LanguageShare) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LanguageShare) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

var File_realtime_me_v1_projects_proto protoreflect.FileDescriptor

const file_realtime_me_v1_projects_proto_rawDesc = "" +
	"\n" +
	"\x1drealtime/me/v1/projects.proto\x12\x0erealtime.me.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n" +
	"\x13ListProjectsRequest\"K\n" +
	"\x14ListProjectsResponse\x123\n" +
	"\bprojects\x18\x01 \x03(\v2\x17.realtime.me.v1.ProjectR\bprojects\"\xea\x04\n" +
	"\aProject\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12A\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2!.realtime.me.v1.ProjectVisibilityR\n" +
	"visibility\x12)\n" +
	"\x10primary_language\x18\x06 \x01(\tR\x0fprimaryLanguage\x12\x16\n" +
	"\x06topics\x18\a \x03(\tR\x06topics\x12\x1d\n" +
	"\n" +
	"star_count\x18\b \x01(\x05R\tstarCount\x12%\n" +
	"\x0erepository_url\x18\t \x01(\tR\rrepositoryUrl\x12!\n" +
	"\fhomepage_url\x18\n" +
	" \x01(\tR\vhomepageUrl\x12@\n" +
	"\x0elast_push_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\flastPushTime\x12;\n" +
	"\vcreate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x1a\n" +
	"\barchived\x18\r \x01(\bR\barchived\x12;\n" +
	"\tlanguages\x18\x0e \x03(\v2\x1d.realtime.me.v1.LanguageShareR\tlanguages\x12'\n" +
	"\x0fcommit_activity\x18\x0f \x03(\x05R\x0ecommitActivity\"9\n" +
	"\rLanguageShare\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes*v\n" +
	"\x11ProjectVisibility\x12\"\n" +
	"\x1ePROJECT_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PROJECT_VISIBILITY_PUBLIC\x10\x01\x12\x1e\n" +
	"\x1aPROJECT_VISIBILITY_PRIVATE\x10\x022l\n" +
	"\x0fProjectsService\x12Y\n" +
	"\fListProjects\x12#.realtime.me.v1.ListProjectsRequest\x1a$.realtime.me.v1.ListProjectsResponseB\xc4\x01\n" +
	"\x12com.realtime.me.v1B\rProjectsProtoP\x01ZEgithub.com/pood1e/realtime-me/services/status/internal/genproto/realtime/me/v1;mev1\xa2\x02\x03RMX\xaa\x02\x0eRealtime.Me.V1\xca\x02\x0eRealtime\\Me\\V1\xe2\x02\x1aRealtime\\Me\\V1\\GPBMetadata\xea\x02\x10Realtime::Me::V1b\x06proto3"

var (
	file_realtime_me_v1_projects_proto_rawDescOnce sync.Once
	file_realtime_me_v1_projects_proto_rawDescData []byte
)

func file_realtime_me_v1_projects_proto_rawDescGZIP() []byte {
	file_realtime_me_v1_projects_proto_rawDescOnce.Do(func() {
		file_realtime_me_v1_projects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtime_me_v1_projects_proto_rawDesc), len(file_realtime_me_v1_projects_proto_rawDesc)))
	})
	return file_realtime_me_v1_projects_proto_rawDescData
}

var file_realtime_me_v1_projects_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_realtime_me_v1_projects_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_realtime_me_v1_projects_proto_goTypes = []any{
	(ProjectVisibility)(0),        // 0: realtime.me.v1.ProjectVisibility
	(*ListProjectsRequest)(nil),   // 1: realtime.me.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),  // 2: realtime.me.v1.ListProjectsResponse
	(*Project)(nil),               // 3: realtime.me.v1.Project
	(*LanguageShare)(nil),         // 4: realtime.me.v1.LanguageShare
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_realtime_me_v1_projects_proto_depIdxs = []int32{
	3, // 0: realtime.me.v1.ListProjectsResponse.projects:type_name -> realtime.me.v1.Project
	0, // 1: realtime.me.v1.Project.visibility:type_name -> realtime.me.v1.ProjectVisibility
	5, // 2: realtime.me.v1.Project.last_push_time:type_name -> google.protobuf.Timestamp
	5, // 3: realtime.me.v1.Project.create_time:type_name -> google.protobuf.Timestamp
	4, // 4: realtime.me.v1.Project.languages:type_name -> realtime.me.v1.LanguageShare
	1, // 5: realtime.me.v1.ProjectsService.ListProjects:input_type -> realtime.me.v1.ListProjectsRequest
	2, // 6: realtime.me.v1.ProjectsService.ListProjects:output_type -> realtime.me.v1.ListProjectsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_realtime_me_v1_projects_proto_init() }
func file_realtime_me_v1_projects_proto_init() {
	if File_realtime_me_v1_projects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtime_me_v1_projects_proto_rawDesc), len(file_realtime_me_v1_projects_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realtime_me_v1_projects_proto_goTypes,
		DependencyIndexes: file_realtime_me_v1_projects_proto_depIdxs,
		EnumInfos:         file_realtime_me_v1_projects_proto_enumTypes,
		MessageInfos:      file_realtime_me_v1_projects_proto_msgTypes,
	}.Build()
	File_realtime_me_v1_projects_proto = out.File
	file_realtime_me_v1_projects_proto_goTypes = nil
	file_realtime_me_v1_projects_proto_depIdxs = nil
}
