// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: realtime/me/v1/status_types.proto

package mev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceKind is the broad category of a reporting device.
type DeviceKind int32

const (
	// Kind is not known.
	DeviceKind_DEVICE_KIND_UNSPECIFIED DeviceKind = 0
	// A physical host machine.
	DeviceKind_DEVICE_KIND_HOST DeviceKind = 1
	// A virtual machine running on a host.
	DeviceKind_DEVICE_KIND_VIRTUAL_MACHINE DeviceKind = 2
	// A phone companion.
	DeviceKind_DEVICE_KIND_PHONE DeviceKind = 3
	// A watch paired to a phone.
	DeviceKind_DEVICE_KIND_WATCH DeviceKind = 4
)

// Enum value maps for DeviceKind.
var (
	DeviceKind_name = map[int32]string{
		0: "DEVICE_KIND_UNSPECIFIED",
		1: "DEVICE_KIND_HOST",
		2: "DEVICE_KIND_VIRTUAL_MACHINE",
		3: "DEVICE_KIND_PHONE",
		4: "DEVICE_KIND_WATCH",
	}
	DeviceKind_value = map[string]int32{
		"DEVICE_KIND_UNSPECIFIED":     0,
		"DEVICE_KIND_HOST":            1,
		"DEVICE_KIND_VIRTUAL_MACHINE": 2,
		"DEVICE_KIND_PHONE":           3,
		"DEVICE_KIND_WATCH":           4,
	}
)

func (x DeviceKind) Enum() *DeviceKind {
	p := new(DeviceKind)
	*p = x
	return p
}

func (x DeviceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_me_v1_status_types_proto_enumTypes[0].Descriptor()
}

func (DeviceKind) Type() protoreflect.EnumType {
	return &file_realtime_me_v1_status_types_proto_enumTypes[0]
}

func (x DeviceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceKind.Descriptor instead.
func (DeviceKind) EnumDescriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_types_proto_rawDescGZIP(), []int{0}
}

// DeviceRole is the operational role a device plays on the status surface.
type DeviceRole int32

const (
	// Role is not known.
	DeviceRole_DEVICE_ROLE_UNSPECIFIED DeviceRole = 0
	// The always-on server that also hosts the gateway.
	DeviceRole_DEVICE_ROLE_SERVER DeviceRole = 1
	// A personal desktop or laptop.
	DeviceRole_DEVICE_ROLE_DESKTOP DeviceRole = 2
	// A virtual machine guest.
	DeviceRole_DEVICE_ROLE_VM DeviceRole = 3
)

// Enum value maps for DeviceRole.
var (
	DeviceRole_name = map[int32]string{
		0: "DEVICE_ROLE_UNSPECIFIED",
		1: "DEVICE_ROLE_SERVER",
		2: "DEVICE_ROLE_DESKTOP",
		3: "DEVICE_ROLE_VM",
	}
	DeviceRole_value = map[string]int32{
		"DEVICE_ROLE_UNSPECIFIED": 0,
		"DEVICE_ROLE_SERVER":      1,
		"DEVICE_ROLE_DESKTOP":     2,
		"DEVICE_ROLE_VM":          3,
	}
)

func (x DeviceRole) Enum() *DeviceRole {
	p := new(DeviceRole)
	*p = x
	return p
}

func (x DeviceRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceRole) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_me_v1_status_types_proto_enumTypes[1].Descriptor()
}

func (DeviceRole) Type() protoreflect.EnumType {
	return &file_realtime_me_v1_status_types_proto_enumTypes[1]
}

func (x DeviceRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceRole.Descriptor instead.
func (DeviceRole) EnumDescriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_types_proto_rawDescGZIP(), []int{1}
}

// OnlineState is whether a device is currently reachable.
type OnlineState int32

const (
	// Reachability is not known.
	OnlineState_ONLINE_STATE_UNSPECIFIED OnlineState = 0
	// The device is reachable.
	OnlineState_ONLINE_STATE_ONLINE OnlineState = 1
	// The device is not reachable.
	OnlineState_ONLINE_STATE_OFFLINE OnlineState = 2
)

// Enum value maps for OnlineState.
var (
	OnlineState_name = map[int32]string{
		0: "ONLINE_STATE_UNSPECIFIED",
		1: "ONLINE_STATE_ONLINE",
		2: "ONLINE_STATE_OFFLINE",
	}
	OnlineState_value = map[string]int32{
		"ONLINE_STATE_UNSPECIFIED": 0,
		"ONLINE_STATE_ONLINE":      1,
		"ONLINE_STATE_OFFLINE":     2,
	}
)

func (x OnlineState) Enum() *OnlineState {
	p := new(OnlineState)
	*p = x
	return p
}

func (x OnlineState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnlineState) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_me_v1_status_types_proto_enumTypes[2].Descriptor()
}

func (OnlineState) Type() protoreflect.EnumType {
	return &file_realtime_me_v1_status_types_proto_enumTypes[2]
}

func (x OnlineState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnlineState.Descriptor instead.
func (OnlineState) EnumDescriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_types_proto_rawDescGZIP(), []int{2}
}

// NetworkState is a phone's current network transport.
type NetworkState int32

const (
	// Transport is not known.
	NetworkState_NETWORK_STATE_UNSPECIFIED NetworkState = 0
	// No network is available.
	NetworkState_NETWORK_STATE_OFFLINE NetworkState = 1
	// Connected over Wi-Fi.
	NetworkState_NETWORK_STATE_WIFI NetworkState = 2
	// Connected over a cellular network.
	NetworkState_NETWORK_STATE_CELLULAR NetworkState = 3
	// Connected through a VPN.
	NetworkState_NETWORK_STATE_VPN NetworkState = 4
	// Online over an unspecified transport.
	NetworkState_NETWORK_STATE_ONLINE NetworkState = 5
)

// Enum value maps for NetworkState.
var (
	NetworkState_name = map[int32]string{
		0: "NETWORK_STATE_UNSPECIFIED",
		1: "NETWORK_STATE_OFFLINE",
		2: "NETWORK_STATE_WIFI",
		3: "NETWORK_STATE_CELLULAR",
		4: "NETWORK_STATE_VPN",
		5: "NETWORK_STATE_ONLINE",
	}
	NetworkState_value = map[string]int32{
		"NETWORK_STATE_UNSPECIFIED": 0,
		"NETWORK_STATE_OFFLINE":     1,
		"NETWORK_STATE_WIFI":        2,
		"NETWORK_STATE_CELLULAR":    3,
		"NETWORK_STATE_VPN":         4,
		"NETWORK_STATE_ONLINE":      5,
	}
)

func (x NetworkState) Enum() *NetworkState {
	p := new(NetworkState)
	*p = x
	return p
}

func (x NetworkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkState) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_me_v1_status_types_proto_enumTypes[3].Descriptor()
}

func (NetworkState) Type() protoreflect.EnumType {
	return &file_realtime_me_v1_status_types_proto_enumTypes[3]
}

func (x NetworkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkState.Descriptor instead.
func (NetworkState) EnumDescriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_types_proto_rawDescGZIP(), []int{3}
}

// AgentState is the run state of a coding agent.
type AgentState int32

const (
	// State is not known.
	AgentState_AGENT_STATE_UNSPECIFIED AgentState = 0
	// The agent is idle.
	AgentState_AGENT_STATE_IDLE AgentState = 1
	// The agent is actively running a task.
	AgentState_AGENT_STATE_RUNNING AgentState = 2
	// The agent's last task failed.
	AgentState_AGENT_STATE_FAILED AgentState = 3
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0: "AGENT_STATE_UNSPECIFIED",
		1: "AGENT_STATE_IDLE",
		2: "AGENT_STATE_RUNNING",
		3: "AGENT_STATE_FAILED",
	}
	AgentState_value = map[string]int32{
		"AGENT_STATE_UNSPECIFIED": 0,
		"AGENT_STATE_IDLE":        1,
		"AGENT_STATE_RUNNING":     2,
		"AGENT_STATE_FAILED":      3,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_me_v1_status_types_proto_enumTypes[4].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_realtime_me_v1_status_types_proto_enumTypes[4]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_types_proto_rawDescGZIP(), []int{4}
}

// Accessory is a connected peripheral, such as a Bluetooth audio device.
type Accessory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is a lowercase accessory category key, such as "bluetooth_audio".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// display_name is the human-readable accessory label.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// model is the accessory hardware model, if known.
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// battery_percent is the accessory battery level from 0 to 100, if reported.
	BatteryPercent *int32 `protobuf:"varint,4,opt,name=battery_percent,json=batteryPercent,proto3,oneof" json:"battery_percent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Accessory) Reset() {
	*x = Accessory{}
	mi := &file_realtime_me_v1_status_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accessory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accessory) ProtoMessage() {}

func (x *Accessory) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accessory.ProtoReflect.Descriptor instead.
func (*Accessory) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_types_proto_rawDescGZIP(), []int{0}
}

func (x *Accessory) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Accessory) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Accessory) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Accessory) GetBatteryPercent() int32 {
	if x != nil && x.BatteryPercent != nil {
		return *x.BatteryPercent
	}
	return 0
}

// MediaStatus is the media item a device is currently playing.
type MediaStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// title is the track or media title.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// artist is the performing artist, if known.
	Artist        string `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaStatus) Reset() {
	*x = MediaStatus{}
	mi := &file_realtime_me_v1_status_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaStatus) ProtoMessage() {}

func (x *MediaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaStatus.ProtoReflect.Descriptor instead.
func (*MediaStatus) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_types_proto_rawDescGZIP(), []int{1}
}

func (x *MediaStatus) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MediaStatus) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

// SwitchPresence is the Nintendo Switch play presence reported by the owner's
// Android device. It intentionally carries only public presence facts, never
// Nintendo tokens or account identifiers.
type SwitchPresence struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// state is whether the Switch presence is currently online.
	State OnlineState `protobuf:"varint,1,opt,name=state,proto3,enum=realtime.me.v1.OnlineState" json:"state,omitempty"`
	// game_name is the currently played title, if Nintendo reports one.
	GameName string `protobuf:"bytes,2,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	// title_id is Nintendo's title identifier for the current game, if present.
	TitleId string `protobuf:"bytes,3,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	// image_uri is the title image Nintendo returns for the current game.
	ImageUri string `protobuf:"bytes,4,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	// presence_update_time is Nintendo's timestamp for the presence record.
	PresenceUpdateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=presence_update_time,json=presenceUpdateTime,proto3" json:"presence_update_time,omitempty"`
	// logout_time is Nintendo's last logout timestamp, when reported.
	LogoutTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=logout_time,json=logoutTime,proto3" json:"logout_time,omitempty"`
	// fetch_time is when the reporting APK fetched this presence.
	FetchTime     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=fetch_time,json=fetchTime,proto3" json:"fetch_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchPresence) Reset() {
	*x = SwitchPresence{}
	mi := &file_realtime_me_v1_status_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchPresence) ProtoMessage() {}

func (x *SwitchPresence) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchPresence.ProtoReflect.Descriptor instead.
func (*SwitchPresence) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_types_proto_rawDescGZIP(), []int{2}
}

func (x *SwitchPresence) GetState() OnlineState {
	if x != nil {
		return x.State
	}
	return OnlineState_ONLINE_STATE_UNSPECIFIED
}

func (x *SwitchPresence) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *SwitchPresence) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

func (x *SwitchPresence) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *SwitchPresence) GetPresenceUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PresenceUpdateTime
	}
	return nil
}

func (x *SwitchPresence) GetLogoutTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LogoutTime
	}
	return nil
}

func (x *SwitchPresence) GetFetchTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchTime
	}
	return nil
}

// MetricSample is one OpenTelemetry-named numeric sample reported by a host.
type MetricSample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the OpenTelemetry metric name, such as "system.cpu.utilization".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// unit is the UCUM unit annotation, such as "By" or "1".
	Unit string `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	// value is the sample value.
	Value float64 `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	// attributes are OpenTelemetry attributes attached to the sample.
	Attributes    map[string]string `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_realtime_me_v1_status_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_types_proto_rawDescGZIP(), []int{3}
}

func (x *MetricSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricSample) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricSample) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// PhoneState is the phone's own device state, excluding the paired watch.
type PhoneState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// battery_percent is the phone battery level from 0 to 100, if reported.
	BatteryPercent *int32 `protobuf:"varint,1,opt,name=battery_percent,json=batteryPercent,proto3,oneof" json:"battery_percent,omitempty"`
	// charge_state is the phone charging state.
	ChargeState ChargeState `protobuf:"varint,2,opt,name=charge_state,json=chargeState,proto3,enum=realtime.me.v1.ChargeState" json:"charge_state,omitempty"`
	// network is the phone's current network transport.
	Network NetworkState `protobuf:"varint,3,opt,name=network,proto3,enum=realtime.me.v1.NetworkState" json:"network,omitempty"`
	// accessories are peripherals connected to the phone.
	Accessories   []*Accessory `protobuf:"bytes,4,rep,name=accessories,proto3" json:"accessories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneState) Reset() {
	*x = PhoneState{}
	mi := &file_realtime_me_v1_status_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneState) ProtoMessage() {}

func (x *PhoneState) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_me_v1_status_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneState.ProtoReflect.Descriptor instead.
func (*PhoneState) Descriptor() ([]byte, []int) {
	return file_realtime_me_v1_status_types_proto_rawDescGZIP(), []int{4}
}

func (x *PhoneState) GetBatteryPercent() int32 {
	if x != nil && x.BatteryPercent != nil {
		return *x.BatteryPercent
	}
	return 0
}

func (x *PhoneState) GetChargeState() ChargeState {
	if x != nil {
		return x.ChargeState
	}
	return ChargeState_CHARGE_STATE_UNSPECIFIED
}

func (x *PhoneState) GetNetwork() NetworkState {
	if x != nil {
		return x.Network
	}
	return NetworkState_NETWORK_STATE_UNSPECIFIED
}

func (x *PhoneState) GetAccessories() []*Accessory {
	if x != nil {
		return x.Accessories
	}
	return nil
}

var File_realtime_me_v1_status_types_proto protoreflect.FileDescriptor

const file_realtime_me_v1_status_types_proto_rawDesc = "" +
	"\n" +
	"!realtime/me/v1/status_types.proto\x12\x0erealtime.me.v1\x1a\x1arealtime/me/v1/watch.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x01\n" +
	"\tAccessory\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12,\n" +
	"\x0fbattery_percent\x18\x04 \x01(\x05H\x00R\x0ebatteryPercent\x88\x01\x01B\x12\n" +
	"\x10_battery_percent\"L\n" +
	"\vMediaStatus\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artistJ\x04\b\x03\x10\x04R\tcover_url\"\xde\x02\n" +
	"\x0eSwitchPresence\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.realtime.me.v1.OnlineStateR\x05state\x12\x1b\n" +
	"\tgame_name\x18\x02 \x01(\tR\bgameName\x12\x19\n" +
	"\btitle_id\x18\x03 \x01(\tR\atitleId\x12\x1b\n" +
	"\timage_uri\x18\x04 \x01(\tR\bimageUri\x12L\n" +
	"\x14presence_update_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12presenceUpdateTime\x12;\n" +
	"\vlogout_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"logoutTime\x129\n" +
	"\n" +
	"fetch_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tfetchTime\"\xd9\x01\n" +
	"\fMetricSample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12L\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2,.realtime.me.v1.MetricSample.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\n" +
	"PhoneState\x12,\n" +
	"\x0fbattery_percent\x18\x01 \x01(\x05H\x00R\x0ebatteryPercent\x88\x01\x01\x12>\n" +
	"\fcharge_state\x18\x02 \x01(\x0e2\x1b.realtime.me.v1.ChargeStateR\vchargeState\x126\n" +
	"\anetwork\x18\x03 \x01(\x0e2\x1c.realtime.me.v1.NetworkStateR\anetwork\x12;\n" +
	"\vaccessories\x18\x04 \x03(\v2\x19.realtime.me.v1.AccessoryR\vaccessoriesB\x12\n" +
	"\x10_battery_percent*\x8e\x01\n" +
	"\n" +
	"DeviceKind\x12\x1b\n" +
	"\x17DEVICE_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DEVICE_KIND_HOST\x10\x01\x12\x1f\n" +
	"\x1bDEVICE_KIND_VIRTUAL_MACHINE\x10\x02\x12\x15\n" +
	"\x11DEVICE_KIND_PHONE\x10\x03\x12\x15\n" +
	"\x11DEVICE_KIND_WATCH\x10\x04*n\n" +
	"\n" +
	"DeviceRole\x12\x1b\n" +
	"\x17DEVICE_ROLE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DEVICE_ROLE_SERVER\x10\x01\x12\x17\n" +
	"\x13DEVICE_ROLE_DESKTOP\x10\x02\x12\x12\n" +
	"\x0eDEVICE_ROLE_VM\x10\x03*^\n" +
	"\vOnlineState\x12\x1c\n" +
	"\x18ONLINE_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ONLINE_STATE_ONLINE\x10\x01\x12\x18\n" +
	"\x14ONLINE_STATE_OFFLINE\x10\x02*\xad\x01\n" +
	"\fNetworkState\x12\x1d\n" +
	"\x19NETWORK_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15NETWORK_STATE_OFFLINE\x10\x01\x12\x16\n" +
	"\x12NETWORK_STATE_WIFI\x10\x02\x12\x1a\n" +
	"\x16NETWORK_STATE_CELLULAR\x10\x03\x12\x15\n" +
	"\x11NETWORK_STATE_VPN\x10\x04\x12\x18\n" +
	"\x14NETWORK_STATE_ONLINE\x10\x05*p\n" +
	"\n" +
	"AgentState\x12\x1b\n" +
	"\x17AGENT_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AGENT_STATE_IDLE\x10\x01\x12\x17\n" +
	"\x13AGENT_STATE_RUNNING\x10\x02\x12\x16\n" +
	"\x12AGENT_STATE_FAILED\x10\x03B\xc7\x01\n" +
	"\x12com.realtime.me.v1B\x10StatusTypesProtoP\x01ZEgithub.com/pood1e/realtime-me/services/status/internal/genproto/realtime/me/v1;mev1\xa2\x02\x03RMX\xaa\x02\x0eRealtime.Me.V1\xca\x02\x0eRealtime\\Me\\V1\xe2\x02\x1aRealtime\\Me\\V1\\GPBMetadata\xea\x02\x10Realtime::Me::V1b\x06proto3"

var (
	file_realtime_me_v1_status_types_proto_rawDescOnce sync.Once
	file_realtime_me_v1_status_types_proto_rawDescData []byte
)

func file_realtime_me_v1_status_types_proto_rawDescGZIP() []byte {
	file_realtime_me_v1_status_types_proto_rawDescOnce.Do(func() {
		file_realtime_me_v1_status_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtime_me_v1_status_types_proto_rawDesc), len(file_realtime_me_v1_status_types_proto_rawDesc)))
	})
	return file_realtime_me_v1_status_types_proto_rawDescData
}

var file_realtime_me_v1_status_types_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_realtime_me_v1_status_types_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_realtime_me_v1_status_types_proto_goTypes = []any{
	(DeviceKind)(0),               // 0: realtime.me.v1.DeviceKind
	(DeviceRole)(0),               // 1: realtime.me.v1.DeviceRole
	(OnlineState)(0),              // 2: realtime.me.v1.OnlineState
	(NetworkState)(0),             // 3: realtime.me.v1.NetworkState
	(AgentState)(0),               // 4: realtime.me.v1.AgentState
	(*Accessory)(nil),             // 5: realtime.me.v1.Accessory
	(*MediaStatus)(nil),           // 6: realtime.me.v1.MediaStatus
	(*SwitchPresence)(nil),        // 7: realtime.me.v1.SwitchPresence
	(*MetricSample)(nil),          // 8: realtime.me.v1.MetricSample
	(*PhoneState)(nil),            // 9: realtime.me.v1.PhoneState
	nil,                           // 10: realtime.me.v1.MetricSample.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(ChargeState)(0),              // 12: realtime.me.v1.ChargeState
}
var file_realtime_me_v1_status_types_proto_depIdxs = []int32{
	2,  // 0: realtime.me.v1.SwitchPresence.state:type_name -> realtime.me.v1.OnlineState
	11, // 1: realtime.me.v1.SwitchPresence.presence_update_time:type_name -> google.protobuf.Timestamp
	11, // 2: realtime.me.v1.SwitchPresence.logout_time:type_name -> google.protobuf.Timestamp
	11, // 3: realtime.me.v1.SwitchPresence.fetch_time:type_name -> google.protobuf.Timestamp
	10, // 4: realtime.me.v1.MetricSample.attributes:type_name -> realtime.me.v1.MetricSample.AttributesEntry
	12, // 5: realtime.me.v1.PhoneState.charge_state:type_name -> realtime.me.v1.ChargeState
	3,  // 6: realtime.me.v1.PhoneState.network:type_name -> realtime.me.v1.NetworkState
	5,  // 7: realtime.me.v1.PhoneState.accessories:type_name -> realtime.me.v1.Accessory
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_realtime_me_v1_status_types_proto_init() }
func file_realtime_me_v1_status_types_proto_init() {
	if File_realtime_me_v1_status_types_proto != nil {
		return
	}
	file_realtime_me_v1_watch_proto_init()
	file_realtime_me_v1_status_types_proto_msgTypes[0].OneofWrappers = []any{}
	file_realtime_me_v1_status_types_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtime_me_v1_status_types_proto_rawDesc), len(file_realtime_me_v1_status_types_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_realtime_me_v1_status_types_proto_goTypes,
		DependencyIndexes: file_realtime_me_v1_status_types_proto_depIdxs,
		EnumInfos:         file_realtime_me_v1_status_types_proto_enumTypes,
		MessageInfos:      file_realtime_me_v1_status_types_proto_msgTypes,
	}.Build()
	File_realtime_me_v1_status_types_proto = out.File
	file_realtime_me_v1_status_types_proto_goTypes = nil
	file_realtime_me_v1_status_types_proto_depIdxs = nil
}
