port 1194
proto udp
dev tun0
topology subnet

server 10.66.0.0 255.255.255.0
ifconfig-pool 10.66.0.100 10.66.0.200 255.255.255.0
ifconfig-pool-persist /var/lib/openvpn/realtime-me/ipp.txt
client-config-dir /etc/openvpn/server/realtime-me-ccd
ccd-exclusive
max-clients 32

ca /etc/openvpn/server/realtime-me-pki/ca.crt
cert /etc/openvpn/server/realtime-me-pki/server.crt
key /etc/openvpn/server/realtime-me-pki/server.key
crl-verify /etc/openvpn/server/realtime-me-pki/crl.pem
dh none
remote-cert-tls client
verify-client-cert require

tls-crypt-v2 /etc/openvpn/server/realtime-me-pki/tls-crypt-v2-server.key force-cookie
tls-version-min 1.2
tls-cert-profile preferred
data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
allow-compression no

keepalive 10 60
persist-key
persist-tun
explicit-exit-notify 1
user nobody
group nogroup
verb 3
